include:
  - ./db/compose.yml
services:
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:9.3.0
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=demo@demo.com
      - PGADMIN_DEFAULT_PASSWORD=demo
    ports:
      - 3000:80
