CREATE TABLE IF NOT EXISTS USERS (
    id SERIAL PRIMARY KEY,
    name VARCHAR(20) NOT NULL,
    password VARCHAR(28) NOT null,
    admin BOOLEAN NOT NULL
);

CREATE TABLE IF NOT EXISTS LOCATIONS (
    id SERIAL PRIMARY KEY,
    name VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS BOXES (
    id SERIAL PRIMARY KEY,
    location_id INT NOT NULL,
    name VARCHAR(20) NOT NULL,
    FOREIGN KEY (location_id) REFERENCES LOCATIONS(id)
);

CREATE TABLE IF NOT EXISTS ITEMS (
    id SERIAL PRIMARY KEY,
    box_id INT NOT NULL,
    name VARCHAR(20) NOT NULL,
    count INT NOT NULL,
    last_used TIMESTAMP NOT NULL,
    FOREIGN KEY (box_id) REFERENCES BOXES(id)
);