services:
  postgres:
    container_name: database
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      # - /data/postgres/data:/var/lib/postgresql/data
      - ./setup:/docker-entrypoint-initdb.d/